STM32F4xx HAL Driver: HAL_TimeBase_TIM
HAL_TimeBase_TIM
STM32F4xx_HAL_Driver
Functions
void TIM6_DAC_IRQHandler (void)
This function handles TIM interrupt request.
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the TIM6 as a time base source. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
void HAL_SuspendTick (void)
Suspend Tick increment.
void HAL_ResumeTick (void)
Resume Tick increment.
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
Variables
TIM_HandleTypeDef TimHandle
Detailed Description
Function Documentation
HAL_InitTick()
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the TIM6 as a time base source. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
Note
This function is called automatically at the beginning of program after reset by HAL_Init() or at any time when clock is configured, by HAL_RCC_ClockConfig().
Parameters
TickPriority Tick interrupt priority.
Return values
HAL status
Definition at line 54 of file stm32f4xx_hal_timebase_tim_template.c.
References RCC_ClkInitTypeDef::APB1CLKDivider, TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, HAL_ERROR, HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), HAL_OK, HAL_RCC_GetClockConfig(), HAL_RCC_GetPCLK1Freq(), HAL_TIM_Base_Init(), HAL_TIM_Base_Start_IT(), TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, RCC_HCLK_DIV1, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_COUNTERMODE_UP, TimHandle, and uwTickPrio.
HAL_ResumeTick()
void HAL_ResumeTick (void)
Resume Tick increment.
Note
Enable the tick increment by Enabling TIM6 update interrupt.
Return values
None
Definition at line 141 of file stm32f4xx_hal_timebase_tim_template.c.
References __HAL_TIM_ENABLE_IT, TIM_IT_UPDATE, and TimHandle.
HAL_SuspendTick()
void HAL_SuspendTick (void)
Suspend Tick increment.
Note
Disable the tick increment by disabling TIM6 update interrupt.
Return values
None
Definition at line 130 of file stm32f4xx_hal_timebase_tim_template.c.
References __HAL_TIM_DISABLE_IT, TIM_IT_UPDATE, and TimHandle.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM6 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim TIM handle
Return values
None
Definition at line 155 of file stm32f4xx_hal_timebase_tim_template.c.
References HAL_IncTick().
TIM6_DAC_IRQHandler()
void TIM6_DAC_IRQHandler (void)
This function handles TIM interrupt request.
Return values
None
Definition at line 164 of file stm32f4xx_hal_timebase_tim_template.c.
References HAL_TIM_IRQHandler(), and TimHandle.
Variable Documentation
TimHandle
TIM_HandleTypeDef TimHandle
Definition at line 40 of file stm32f4xx_hal_timebase_tim_template.c.
Referenced by HAL_InitTick(), HAL_ResumeTick(), HAL_SuspendTick(), and TIM6_DAC_IRQHandler().